### ISSUE TITLE
When opening the "Edit Schedule" window the dropdown Listener has no selected value (7.7.3)

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#3655]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Framework version 7.7.3
When opening the window Edit Schedule, the dropdown for Select a Listener has no selected value at first.
When changing the CRON and saving, we get an error:
Key [receiver] may not be empty
When selecting the value for the Listener in the dropdown, we can save.
However, when opening the window again, the dropdown is empty again !

The record in the IBISSCHEDULE table has a value in column RECEIVER, which is shown in the dropdown.

The value should be selected when opening the window.

**Reporter**
Richard van der Stel

**To Reproduce**

**Screenshots**

**Configuration**

**Input**

**Environment**

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: Chrome

**Additional Context**

**Comment by nielsm5** [comment]
This should have been fixed in #3522. It may take a few seconds for the value to resolve.
Are there any (browser)console warnings ?

**Comment by rvdstel** [comment]
There are no warnings and the value is not resolved after waiting a long time.
There is a value in the list, but not shown : 

![image](https://user-images.githubusercontent.com/35798481/191205339-15ed7712-8beb-4952-ba5a-b1373dec9f77.png)

![image](https://user-images.githubusercontent.com/35798481/191205416-158a92ec-c7d0-44b0-a414-affc60f6e515.png)
 
selecting value, save, close window, open window, still empty

**Comment by nielsm5** [comment]
Fixed in #3949 but needs to be backported

**Comment by nielsm5** [comment]
Fixed in the 7.8
