### ISSUE TITLE
Transactions/Connections are left open in db 

### ISSUE THREAD

**Issue by alisihab** [ibissource/iaf#4557]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
I have adapters with EsbJmsListener that have ff configuration. In the adapter, after receiving the message I store that message in ibisstore using messageStoreSender(with maxRetries="3"). The application runs on two nodes.
Scenario:
I put 1000 messages in the ff queue then I let the adapters do the processing. After some time, I get deadlocks which happens when the two nodes insert records in ibisstore table. I see transaction timeouts in the log file.  Again after some time, I see such events in log file 
`nl.nn.adapterframework.core.ListenerException: cannot determine message count: (SQLException) SQLState [XAE07], errorCode [1399]: XAER_RMFAIL: The command cannot be executed when global transaction is in the  ROLLBACK ONLY state
	at nl.nn.adapterframework.jdbc.JdbcMessageBrowser.getMessageCount(JdbcMessageBrowser.java:320) ~[ibis-adapterframework-core-7.8-RC3-20230123.094613.jar:7.8-RC3-20230123.094613]
	at nl.nn.adapterframework.webcontrol.api.ShowConfigurationStatus.mapAdapter(ShowConfigurationStatus.java:720) ~[ibis-adapterframework-core-7.8-RC3-20230123.094613.jar:7.8-RC3-20230123.094613]
	at nl.nn.adapterframework.webcontrol.api.ShowConfigurationStatus.getAdapters(ShowConfigurationStatus.java:119) ~[ibis-adapterframework-core-7.8-RC3-20230123.094613.jar:7.8-RC3-20230123.094613]
	... suppressed 3 lines`

Moreover, when I list the processes in the database I see lots of processes that are in sleep state for a long time(>10000 seconds). 
Therefore almost any call to db gives `The command cannot be executed when global transaction is in the ROLLBACK ONLY state` error even if the call is not transacted

I think either the transactions or the connections are not closed properly after processing fails/ times out.

I'll send an email for the other details.

**Reporter**
Ali

ff: 7.8-RC3-20230123.094613, 7.8-RC3-20230221.160953
transaction manager: btm
db: mariadb 10.4.26

**Comment by tnleeuw** [comment]
On first sight, this sounds reminiscent of a number of issues which we have been looking into over the past week. One issue could be that retry-delay is fighting the transaction timeout.

As a workaround, can you increase the default transaction timeout?

In the 7.8RC3 build which should come soon, the default configuration of transaction timeout should already be more in line with the retry-delay, and there are more options for pooling connections.

It is also important to see why transactions are taking such a long time -- has there been a message that had errors and was retried several times due to that?

**Comment by nielsm5** [comment]
Has this been solved by implementing #4733 ?

**Comment by alisihab** [comment]
Not really. The error is not thrown when the process is transacted. However, for non-transacted operations the error mentioned above still occurs.

**Comment by nielsm5** [comment]
We're going to overhaul and drastically improve our pooling mechanisms as well as the ability to use non-XA and XA datasources in  #4841. As such we would like to close this issue once such a fix has been released. I'm reluctant to backport these changes to the 7.8 unless absolutely required.
