### ISSUE TITLE
Stream not closed when running XsltPipe plus HttpSender witth test a pipeline

### ISSUE THREAD

**Issue by jacodg** [ibissource/iaf#4577]
**Describe the issue**
When testing the below configuration with latest 7.9 SNAPSHOT version test a pipeline will say:

An error occured!

When opening the report in progress with Ladybug the output of the pipeline shows:

context:
content-length: 0
date: Tue, 28 Feb 2023 12:46:34 GMT
Metadata.Charset: ISO-8859-1
Http.StatusCode: 200
Http.ReasonPhrase: 
value:
Waiting for stream to be read, captured and closed...

With 7.8-RC3 everything seems to work fine.

**Reporter**
Jaco de Groot

**To Reproduce**
1. Run an adapter with only the below pipes (xxx needs to be replaced with a valid value, I can provide one when needed)
2. Use test a pipeline with the below input
3. See error

**Screenshots**
\-

**Configuration**
```
			<XsltPipe
				name="Xml to Json"
				xpathExpression="concat('{&quot;temperature&quot;:', /current/temperature/@value, '}')"
			/>
			<SenderPipe	name="Post temperature to ThingsBoard">
				<HttpSender
					url="https://demo.thingsboard.io/api/v1/xxx/telemetry"
					methodType="POST"
					contentType="application/json"
				/>
			</SenderPipe>
```

**Input**
```
<current><temperature value="0"/></current>
```

**Environment**
Not okay with:
```
FF! 7.9-20230224.143242: Frank2Example3
Running on xxx using Apache Tomcat/9.0.68
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 206M, total JVM memory: 692M
Free disk space: 48GB, total disk space: 475GB
Up since: 2023-02-28 13:31:35 (10m) 
```
Okay with:
```
FF! 7.8-RC3: Frank2Example3
Running on xxx using Apache Tomcat/9.0.68
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 274M, total JVM memory: 995M
Free disk space: 48GB, total disk space: 475GB
Up since: 2023-02-28 13:43:34 (26s) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by nielsm5** [comment]
Can't reproduce this? Might have been fixed in #4692.

**Comment by jacodg** [comment]
Did a retest and it is indeed solved. With 7.9-20230224.143242 I still get the error with 7.9-20230706.190017 there's no error.
